site_name: LightNet
site_dir: build/doc/lightnet

nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Documentation:
      - Introduction: Documentation/Introduction.md
      - Project Structure: Documentation/Project-Structure.md
      - Build Options: Documentation/Build-Options.md
      - Data Structures: Documentation/Data-Structures.md
      - Intermediate Representation: Documentation/Intermediate-Representation.md
      - Operator Description: Documentation/Operator-Description.md
      - Optimizer Description: Documentation/Optimizer-Description.md
      - Miscellaneous: Documentation/Miscellaneous.md
  - Hacking: Hacking.md

repo_url: https://github.com/zhaozhixu/LightNet
edit_uri: ""

use_directory_urls: false

theme:
  name: mkdocs
  highlightjs: false

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - def_list
  - admonition

extra_css:
  - css/codehilite.css

extra_javascript:
  - js/baidu_analyse.js

